{
  "icons": {
    "16": "icon16",
    "48": "icon48",
    "128": "icon128"
  },

  "content_scripts": [{
    "css": true,
    "js": true,
    "matches": ["*://*/*"]
  }],

  "browser_action": {
    "default_icon": "icon19",
    "default_title": "__MSG_Kernel_AppName__",
    "default_popup": true
  },

  "background": true,
  "options_page": true,

  "name": "__MSG_Kernel_AppName__",
  "version": "1.8.1",
  "description": "__MSG_Kernel_AppDescription__",
  "default_locale": "en",

  "permissions": ["*://*/*", "tabs", "contextMenus", "webRequest", "webNavigation","webRequestBlocking"],

  "manifest_version": 2,
  "content_security_policy": "script-src 'self' https://ssl.google-analytics.com https://apis.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' http://www.google-analytics.com; connect-src *; media-src http://translate.google.com; object-src 'self'",

  "web_accessible_resources": [
    "/src/kernel/init.js", "/src/hub/content/router.js",
    "/src/hub/content/render.js", "/src/hub/content/handlers.js",
    "/src/ui_views/multi_variants.js", "/src/ext/tpl.js",
    "/src/ext/event.js", "/src/particles/translate_ctt/tcModel.js",
    "/src/ui_components/tooltip/simple.js", "/src/ui_components/tooltip/help.js",
    "/src/templates/helpSelectedTooltip.js", "/src/templates/simpleTooltip.js",
    "/src/ui_components/tooltip/helpSelected.js", "/src/templates/helpTooltip.js",
    "/src/particles/scrollbars/sModel.js", "/src/ui_components/scrollbar/scrollbar.js",
    "/resources/styles/ui_components/tooltip/helpSelected.css",
    "/resources/styles/pages/common/main.css", "/resources/styles/pages/internal/content.css",
    "/resources/styles/ui_components/tooltip/simple.css", "/resources/styles/ui_components/tooltip/help.css",
    "/resources/images/sprites/sprite.png", "/src/particles/listen/lModel.js",
    "/src/ext/audio.js", "/src/ext/dom.js",
    "/resources/images/backgrounds/content.png", "/resources/images/backgrounds/left_right_transition.png"
  ]
}